name: Integração contínua

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost/testdb

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: devpro
          POSTGRES_USER: devpro
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.11.0
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
          cache: pip

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: rodar a flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'

      - name: Rodar testes automáticos
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=dozefatores --cov-report=xml

      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
          

